- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Copy Nginx HTTP config
  ansible.builtin.template:
    src: nginx-http.conf.j2
    dest: /etc/nginx/sites-available/bulletin-board
    mode: "0644"
    owner: root
    group: root
  notify: Restart Nginx

- name: Enable Nginx site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/bulletin-board
    dest: /etc/nginx/sites-enabled/bulletin-board
    state: link
  notify: Restart Nginx
